#!/bin/sh

# Xcode Cloud post-clone hook.
#
# Polaris's .xcodeproj is generated by XcodeGen, not checked in, so Xcode Cloud
# has nothing to build right after cloning. This hook installs XcodeGen and
# generates the project before Xcode Cloud resolves the scheme.
#
# It also opts into the iOS 27 beta feature set (on-device LoRA fine-tuning,
# multimodal receipts, Apple Cash split, conversational Siri) when the build's
# environment sets POLARIS_IOS27. Pair that with an Xcode 27 beta toolchain in
# the workflow to compile the gated paths against the real iOS 27 SDK. Leave it
# unset for a baseline build of the stable iOS 26 paths.
#
# Set up in App Store Connect → Xcode Cloud:
#   * Workflow toolchain: Xcode 27 beta (for the iOS 27 build).
#   * Environment variable: POLARIS_IOS27 = 1 (for the flagged build).
# See docs/iOS27.md.

set -e

echo "ci_post_clone: installing XcodeGen"
brew install xcodegen

# Xcode Cloud runs this from ci_scripts/; XcodeGen needs the repo root.
cd "$CI_PRIMARY_REPOSITORY_PATH"

case "$POLARIS_IOS27" in
  1|YES|yes|true|TRUE)
    echo "ci_post_clone: enabling POLARIS_IOS27 compile flag"
    sed -i '' \
      's/SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""/SWIFT_ACTIVE_COMPILATION_CONDITIONS: "POLARIS_IOS27"/' \
      project.yml
    ;;
  *)
    echo "ci_post_clone: POLARIS_IOS27 not set — building stable iOS 26 paths"
    ;;
esac

echo "ci_post_clone: generating Xcode project"
xcodegen generate

echo "ci_post_clone: done"
